apiVersion: v1
kind: Service
metadata:
  name: lab2-app2-service
  labels:
    app: lab2-app2
spec:
  selector:
    app: lab2-app2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31311
  type: NodePort